language: python

python:
  - 2.7
  - 3.4
  - pypy
  - pypy3

matrix:
  include:
    - python: 3.5
      script: tox -e py35
    - python: 3.6
      script: tox -e flake8
    - python: 3.6
      script: tox -e coverage
    - python: 3.7
      script: tox -e py37
    - python: 3.8
      script: tox -e py38
    - python: 3.9
      script: tox -e py39

before_install:
  - sudo apt-get install -y python-dev gcc

install:
  - pip install cython tox codecov

script:
  - tox -e py

after_success:
  - cd tests && codecov
